/**
 * Copyright (c) 2025 Holger Will
 * Licensed under the MIT License
 * https://opensource.org/licenses/MIT
 * This file is part of the enocean-js project.
 */
export const manufacturerList = [
  { id: 0x000, name: "MANUFACTURER_RESERVED" },
  { id: 0x001, name: "PEHA" },
  { id: 0x002, name: "THERMOKON" },
  { id: 0x003, name: "SERVODAN" },
  { id: 0x004, name: "ECHOFLEX_SOLUTIONS" },
  { id: 0x005, name: "OMNIO_AG or AWAG_ELEKTROTECHNIK_AG" },
  { id: 0x006, name: "HARDMEIER_ELECTRONICS" },
  { id: 0x007, name: "REGULVAR_INC" },
  { id: 0x008, name: "AD_HOC_ELECTRONICS" },
  { id: 0x009, name: "DISTECH_CONTROLS" },
  { id: 0x00a, name: "KIEBACK_AND_PETER" },
  { id: 0x00b, name: "ENOCEAN_GMBH" },
  { id: 0x00c, name: "PROBARE or VICOS_GMBH" },
  { id: 0x00d, name: "ELTAKO" },
  { id: 0x00e, name: "LEVITON" },
  { id: 0x00f, name: "HONEYWELL" },
  { id: 0x010, name: "SPARTAN_PERIPHERAL_DEVICES" },
  { id: 0x011, name: "SIEMENS" },
  { id: 0x012, name: "T_MAC" },
  { id: 0x013, name: "RELIABLE_CONTROLS_CORPORATION" },
  { id: 0x014, name: "ELSNER_ELEKTRONIK_GMBH" },
  { id: 0x015, name: "DIEHL_CONTROLS" },
  { id: 0x016, name: "BSC_COMPUTER" },
  { id: 0x017, name: "S_AND_S_REGELTECHNIK_GMBH" },
  { id: 0x018, name: "ZENO_CONTROLS or MASCO_CORPORATION" },
  { id: 0x019, name: "INTESIS_SOFTWARE_SL" },
  { id: 0x01a, name: "VIESSMANN" },
  { id: 0x01b, name: "LUTUO_TECHNOLOGY" },
  { id: 0x01c, name: "CAN2GO" },
  { id: 0x01d, name: "SAUTER" },
  { id: 0x01e, name: "BOOT_UP" },
  { id: 0x01f, name: "OSRAM_SYLVANIA" },
  { id: 0x020, name: "UNOTECH" },
  { id: 0x021, name: "DELTA_CONTROLS_INC" },
  { id: 0x022, name: "UNITRONIC_AG" },
  { id: 0x023, name: "NANOSENSE" },
  { id: 0x024, name: "THE_S4_GROUP" },
  { id: 0x025, name: "MSR_SOLUTIONS or VEISSMANN_HAUSATOMATION_GMBH" },
  { id: 0x026, name: "GE" },
  { id: 0x027, name: "MAICO" },
  { id: 0x028, name: "RUSKIN_COMPANY" },
  { id: 0x029, name: "MAGNUM_ENERGY_SOLUTIONS" },
  { id: 0x02a, name: "KMC_CONTROLS" },
  { id: 0x02b, name: "ECOLOGIX_CONTROLS" },
  { id: 0x02c, name: "TRIO_2_SYS" },
  { id: 0x02d, name: "AFRISO_EURO_INDEX" },
  { id: 0x02e, name: "WALDMANN_GMBH" },
  { id: 0x030, name: "NEC_PLATFORMS_LTD" },
  { id: 0x031, name: "ITEC_CORPORATION" },
  { id: 0x032, name: "SIMICX_CO_LTD" },
  { id: 0x033, name: "PERMUNDO_GMBH" },
  { id: 0x034, name: "EUROTRONIC_TECHNOLOGY_GMBH" },
  { id: 0x035, name: "ART_JAPAN_CO_LTD" },
  { id: 0x036, name: "TIANSU_AUTOMATION_CONTROL_SYSTE_CO_LTD" },
  { id: 0x037, name: "WEINZIERL_ENGINEERING_GMBH" },
  { id: 0x038, name: "GRUPPO_GIORDANO_IDEA_SPA" },
  { id: 0x039, name: "ALPHAEOS_AG" },
  { id: 0x03a, name: "TAG_TECHNOLOGIES" },
  { id: 0x03b, name: "WATTSTOPPER" },
  { id: 0x03c, name: "PRESSAC_COMMUNICATIONS_LTD" },
  { id: 0x03e, name: "GIGA_CONCEPT" },
  { id: 0x03f, name: "SENSORTEC" },
  { id: 0x040, name: "JAEGER_DIREKT" },
  { id: 0x041, name: "AIR_SYSTEM_COMPONENTS_INC" },
  { id: 0x042, name: "ERMINE_CORP" },
  { id: 0x043, name: "SODA_GMBH" },
  { id: 0x044, name: "EKE_AUTOMATION" },
  { id: 0x045, name: "HOLTER_REGELARMUTREN" },
  { id: 0x046, name: "ID_RF" },
  { id: 0x047, name: "DEUTA_CONTROLS_GMBH" },
  { id: 0x048, name: "EWATTCH" },
  { id: 0x049, name: "MICROPELT" },
  { id: 0x04a, name: "CALEFFI_SPA" },
  { id: 0x04b, name: "DIGITAL_CONCEPTS" },
  { id: 0x04c, name: "EMERSON_CLIMATE_TECHNOLOGIES" },
  { id: 0x04d, name: "ADEE_ELECTRONIC" },
  { id: 0x04e, name: "ALTECON" },
  { id: 0x04f, name: "NANJING_PUTIAN_TELECOMMUNICATIONS" },
  { id: 0x050, name: "TERRALUX" },
  { id: 0x051, name: "MENRED" },
  { id: 0x052, name: "IEXERGY_GMBH" },
  { id: 0x053, name: "OVENTROP_GMBH" },
  { id: 0x054, name: "BUILDING_AUTOMATION_PRODUCTS_INC" },
  { id: 0x055, name: "FUNCTIONAL_DEVICES_INC" },
  { id: 0x056, name: "OGGA" },
  { id: 0x057, name: "ITHO_DAALDEROP" },
  { id: 0x058, name: "RESOL" },
  { id: 0x059, name: "ADVANCED_DEVICES" },
  { id: 0x05a, name: "AUTANI_LCC" },
  { id: 0x05b, name: "DR_RIEDEL_GMBH" },
  { id: 0x05c, name: "HOPPE_HOLDING_AG" },
  { id: 0x05d, name: "SIEGENIA_AUBI_KG" },
  { id: 0x05e, name: "ADEO_SERVICES" },
  { id: 0x05f, name: "EIMSIG_EFP_GMBH" },
  { id: 0x060, name: "VIMAR_SPA" },
  { id: 0x061, name: "GLEN_DIMLAX_GMBH" },
  { id: 0x062, name: "PMDM_GMBH" },
  { id: 0x063, name: "HUBBEL_LIGHTNING" },
  { id: 0x064, name: "DEBFLEX" },
  { id: 0x065, name: "PERIFACTORY_SENSORSYSTEMS" },
  { id: 0x066, name: "WATTY_CORP" },
  { id: 0x067, name: "WAGO_KONTAKTTECHNIK" },
  { id: 0x068, name: "KESSEL" },
  { id: 0x069, name: "AUG_WINKHAUS" },
  { id: 0x06a, name: "DECELECT" },
  { id: 0x06b, name: "MST_INDUSTRIES" },
  { id: 0x06c, name: "BECKER_ANTRIEBE" },
  { id: 0x06d, name: "NEXELEC" },
  { id: 0x06e, name: "WIELAND_ELECTRIC" },
  { id: 0x06f, name: "AVIDSEN" },
  { id: 0x070, name: "CWS_BOCO_INTERNATIONAL" },
  { id: 0x071, name: "ROTO_FRANK" },
  { id: 0x072, name: "ALM_CONTORLS" },
  { id: 0x073, name: "TOMMASO_TECHNOLOGIES" },
  { id: 0x074, name: "REHAU" },
  { id: 0x7ff, name: "MULTI_USER_MANUFACTURER" },
];

export function getManufacturerNameById(id) {
  const entry = manufacturerList.find((m) => m.id === id);
  return entry ? entry.name : "UNKNOWN_MANUFACTURER";
}

export function getManufacturerIdByName(name) {
  const entry = manufacturerList.find(
    (m) => m.name.toUpperCase() === name.toUpperCase()
  );
  return entry ? entry.id : 0x7ff; // Return "MULTI_USER_MANUFACTURER" if not found
}
