/**
 * Copyright (c) 2025 Holger Will
 * Licensed under the MIT License
 * https://opensource.org/licenses/MIT
 * This file is part of the enocean-js project.
 */
export const manufacturerList = [
  { id: 0x000, name: "Manufacturer Reserved" },
  { id: 0x001, name: "PEHA" },
  { id: 0x002, name: "Themokon" },
  { id: 0x003, name: "Servodan" },
  { id: 0x004, name: "Echoflex Solutions" },
  { id: 0x005, name: "Omnio AG or Awag Elektrotechnik AG" },
  { id: 0x006, name: "Hardmeier Electronics" },
  { id: 0x007, name: "Regulvar Inc" },
  { id: 0x008, name: "Ad Hoc Electronics" },
  { id: 0x009, name: "Distech Controls" },
  { id: 0x00a, name: "Kiebeck und Partner" },
  { id: 0x00b, name: "EnOcean GmbH" },
  { id: 0x00c, name: "Probare or Vicos GmbH" },
  { id: 0x00d, name: "Eltako" },
  { id: 0x00e, name: "Leviton" },
  { id: 0x00f, name: "Honeywell" },
  { id: 0x010, name: "Spartan Peripheral Devices" },
  { id: 0x011, name: "Siemens" },
  { id: 0x012, name: "T-MAC" },
  { id: 0x013, name: "Reliable Controls Corporation" },
  { id: 0x014, name: "Elsner Elektronik GmbH" },
  { id: 0x015, name: "Diehl Controls" },
  { id: 0x016, name: "BSC Computer" },
  { id: 0x017, name: "S and S Regeltechnik GmbH" },
  { id: 0x018, name: "Zeno Controls or Masco Corporation" },
  { id: 0x019, name: "Intesis Software SL" },
  { id: 0x01a, name: "Viessmann" },
  { id: 0x01b, name: "Lutuo Technology" },
  { id: 0x01c, name: "CAN2GO" },
  { id: 0x01d, name: "Sauter" },
  { id: 0x01e, name: "Boot Up" },
  { id: 0x01f, name: "OSRAM" },
  { id: 0x020, name: "Unotech" },
  { id: 0x021, name: "Delta Controls Inc" },
  { id: 0x022, name: "UniTronic AG" },
  { id: 0x023, name: "NanoSense" },
  { id: 0x024, name: "The S4 Group" },
  { id: 0x025, name: "Viessmann Hausautomation GMBH" },
  { id: 0x026, name: "GE" },
  { id: 0x027, name: "MAICO" },
  { id: 0x028, name: "Ruskin Company" },
  { id: 0x029, name: "Magnum Energy Solutions" },
  { id: 0x02a, name: "KMC Controlls" },
  { id: 0x02b, name: "Ecologix Controls" },
  { id: 0x02c, name: "Trio 2 Sys" },
  { id: 0x02d, name: "Afriso" },
  { id: 0x02e, name: "Waldmann GmbH" },
  { id: 0x030, name: "NEC Platforms Ltd" },
  { id: 0x031, name: "ITEC Corporation" },
  { id: 0x032, name: "Simicx Co Ltd" },
  { id: 0x033, name: "Permundo GmbH" },
  { id: 0x034, name: "Eurotronic Technology GmbH" },
  { id: 0x035, name: "Art Japan Co Ltd" },
  { id: 0x036, name: "Tiansu Automation Control System Co Ltd" },
  { id: 0x037, name: "Weinzierl Engineering GmbH" },
  { id: 0x038, name: "Gruppo Giordano Idea Spa" },
  { id: 0x039, name: "AlphaEOS AG" },
  { id: 0x03a, name: "TAG Technologies" },
  { id: 0x03b, name: "Wattstopper" },
  { id: 0x03c, name: "Pressac Communications Ltd" },
  { id: 0x03e, name: "Giga Concept" },
  { id: 0x03f, name: "SENSORTEC" },
  { id: 0x040, name: "Jaeger Direct" },
  { id: 0x041, name: "AIR System Components Inc" },
  { id: 0x042, name: "Ermine Corp" },
  { id: 0x043, name: "SODA GmbH" },
  { id: 0x044, name: "EKE Automation" },
  { id: 0x045, name: "Holter Regelarmutren" },
  { id: 0x046, name: "NodOn" },
  { id: 0x047, name: "DEUTA Controls GmbH" },
  { id: 0x048, name: "EWATTCH" },
  { id: 0x049, name: "Micropelt" },
  { id: 0x04a, name: "Caleffi Spa" },
  { id: 0x04b, name: "Digital Concepts" },
  { id: 0x04c, name: "Emerson Climate Technologies" },
  { id: 0x04d, name: "Adee Electronic" },
  { id: 0x04e, name: "Altecon" },
  { id: 0x04f, name: "Nanjing Putian Telecommunications" },
  { id: 0x050, name: "Terralux" },
  { id: 0x051, name: "MenRed" },
  { id: 0x052, name: "ieXergy GmbH" },
  { id: 0x053, name: "Oventrop GmbH" },
  { id: 0x054, name: "Building Automation Products Inc" },
  { id: 0x055, name: "Functional Devices Inc" },
  { id: 0x056, name: "OGGA" },
  { id: 0x057, name: "ITHO Daalderop" },
  { id: 0x058, name: "RESOL" },
  { id: 0x059, name: "Advanced Devices" },
  { id: 0x05a, name: "Autani LLC" },
  { id: 0x05b, name: "Dr Riedel GmbH" },
  { id: 0x05c, name: "Hoppe Holding AG" },
  { id: 0x05d, name: "Siegenia Aubi GmbH" },
  { id: 0x05e, name: "Adeo Services" },
  { id: 0x05f, name: "Eimsig EFP GmbH" },
  { id: 0x060, name: "Vimar Spa" },
  { id: 0x061, name: "Glen Dimlax GmbH" },
  { id: 0x062, name: "PMDM GmbH" },
  { id: 0x063, name: "Hubbell Lighting" },
  { id: 0x064, name: "Debflex" },
  { id: 0x065, name: "Perifactory Sensorsystems" },
  { id: 0x066, name: "Watty Corp" },
  { id: 0x067, name: "Wago Kontakttechnik" },
  { id: 0x068, name: "Kessel" },
  { id: 0x069, name: "Aug Winkhaus" },
  { id: 0x06a, name: "Decelect" },
  { id: 0x06b, name: "MST Industries" },
  { id: 0x06c, name: "Becker Antriebe" },
  { id: 0x06d, name: "Nexelec" },
  { id: 0x06e, name: "Wieland Electric" },
  { id: 0x06f, name: "Avidsen" },
  { id: 0x070, name: "CWS BOCO International" },
  { id: 0x071, name: "Roto Frank" },
  { id: 0x072, name: "ALM Controls" },
  { id: 0x073, name: "Tomasso Technologies" },
  { id: 0x074, name: "REHAU" },
  { id: 0x230, name: "NodOn" },
  { id: 0x7ff, name: "Diverse" },
];

export function getManufacturerNameById(id) {
  const entry = manufacturerList.find((m) => m.id === id);
  return entry ? entry.name : "UNKNOWN_MANUFACTURER";
}

export function getManufacturerIdByName(name) {
  const entry = manufacturerList.find(
    (m) => m.name.toUpperCase() === name.toUpperCase()
  );
  return entry ? entry.id : 0x7ff; // Return "MULTI_USER_MANUFACTURER" if not found
}
